import tkinter as T
win=T.Tk()
win.geometry("550x300+100+200")
win.title("OPERATIONEN")
l1=T.Label(text="Multiplikation",bg="black",fg="white",borderwidth=5)
l1.grid(row=0,column=0)
l2=T.Label(text="Gib die erste Zahl ein:")
l2.grid(row=1,column=0)
e1=T.Entry(width=20,borderwidth=5)
e1.grid(row=2,column=0)
l3=T.Label(text="Gib die zweite Zahl ein:")
l3.grid(row=3,column=0)
e2=T.Entry(width=20,borderwidth=5)
e2.grid(row=4,column=0)
def mal ():
    v1=float(e1.get())
    v2=float(e2.get())
    v=v1*v2 
    l5=T.Label(text=v)
    l5.grid(row=7,column=0)
    return v
b1=T.Button(text="Rechnen",width=10,borderwidth=5,command=mal)
b1.grid(row=5,column=0)
l4=T.Label(text="Das Ergebniss :",bg="light green",fg="black")
l4.grid(row=6,column=0)

l6=T.Label(text="Addition",bg="black",fg="white",borderwidth=5)
l6.grid(row=0,column=1)
l7=T.Label(text="Gib die erste Zahl ein:")
l7.grid(row=1,column=1)
e3=T.Entry(width=20,borderwidth=5)
e3.grid(row=2,column=1)
l8=T.Label(text="Gib die zweite Zahl ein:")
l8.grid(row=3,column=1)
e4=T.Entry(width=20,borderwidth=5)
e4.grid(row=4,column=1)
def addieren ():
    v1=float(e3.get())
    v2=float(e4.get())
    v=v1+v2 
    l10=T.Label(text=v)
    l10.grid(row=7,column=1)
    return v
b2=T.Button(text="Rechnen",width=10,borderwidth=5,command=addieren)
b2.grid(row=5,column=1)
l9=T.Label(text="Das Ergebniss :",bg="light green",fg="black")
l9.grid(row=6,column=1)

l11=T.Label(text="Subtraktion",bg="black",fg="white",borderwidth=5)
l11.grid(row=0,column=2)
l12=T.Label(text="Gib die erste Zahl ein:")
l12.grid(row=1,column=2)
e5=T.Entry(width=20,borderwidth=5)
e5.grid(row=2,column=2)
l13=T.Label(text="Gib die zweite Zahl ein:")
l13.grid(row=3,column=2)
e6=T.Entry(width=20,borderwidth=5)
e6.grid(row=4,column=2)
def sub ():
    v1=float(e5.get())
    v2=float(e6.get())
    v=v1-v2 
    l15=T.Label(text=v)
    l15.grid(row=7,column=2)
    return v
b3=T.Button(text="Rechnen",width=10,borderwidth=5,command=sub)
b3.grid(row=5,column=2)
l14=T.Label(text="Das Ergebniss :",bg="light green",fg="black")
l14.grid(row=6,column=2)

l16=T.Label(text="Division",bg="black",fg="white",borderwidth=5)
l16.grid(row=0,column=3)
l17=T.Label(text="Gib die erste Zahl ein:")
l17.grid(row=1,column=3)
e7=T.Entry(width=20,borderwidth=3)
e7.grid(row=2,column=3)
l18=T.Label(text="Gib die zweite Zahl ein:")
l18.grid(row=3,column=3)
e8=T.Entry(width=20,borderwidth=5)
e8.grid(row=4,column=3)
def sub ():
    v1=float(e7.get())
    v2=float(e8.get())
    v=v1/v2 
    l20=T.Label(text=v)
    l20.grid(row=7,column=3)
    return v
b4=T.Button(text="Rechnen",width=10,borderwidth=5,command=sub)
b4.grid(row=5,column=3)
l19=T.Label(text="Das Ergebniss :",bg="light green",fg="black")
l19.grid(row=6,column=3)

win.mainloop()